const charDB = {
    huey: {
        fullName: 'Hubert "Huey" Duck',
        firstName: "Hubert",
        lastName: "Duck",
        personality: "smart, analytical, precarious",
        gender: "male",
        age: 12,
        occupation: "Senior Junior Woodchuck Scout",
        voicedBy: "Danny Pudi",
    },
    dewey: {
        fullName: 'Dewford Dingus "Dewey" Duck',
        firstName: "Dewford",
        lastName: "Duck",
        personality: "daring, attention-seeking, adventerous",
        gender: "male",
        age: 12,
        occupation: "Senior Junior Woodchuck Scout",
        voicedBy: "Ben Schwartz",
    },
    louie: {
        fullName: 'Llewellyn "Louie" Duck',
        firstName: "Llewellyn",
        lastName: "Duck",
        personality: "laid-back, resourceful, lazy",
        gender: "male",
        age: 12,
        occupation: "Senior Junior Woodchuck Scout",
        voicedBy: "Bobby Moynihan",
    },
    webby: {
        fullName: 'Webbigail "Webb" Vanderquack',
        firstName: "Webbigail",
        lastName: "Vanderquack",
        personality: "adventurous, zealous, eager",
        gender: "female",
        age: 12,
        occupation: "unknown",
        voicedBy: "Kate Micucci",
    },
    scrooge: {
        fullName: "Scrooge McDuck",
        firstName: "Scrooge",
        lastName: "McDuck",
        personality: "stern, kind-hearted, self-righteous",
        gender: "male",
        age: 155,
        occupation: "businessman",
        voicedBy: "David Tennant",
    },
    donald: {
        fullName: "Donald Fauntleroy Duck",
        firstName: "Donald",
        lastName: "Duck",
        personality: "fiery, devoted, independent",
        gender: "male",
        age: 36,
        occupation: "Sailor",
        voicedBy: "Tony Anselmo",
    },
    daisy: {
        fullName: "Daisy Duck",
        firstName: "Daisy",
        lastName: "Duck",
        personality: "nice, calm, clever",
        gender: "female",
        age: 0,
        occupation: "unknown",
        voicedBy: "Tress MacNeille",
    },
    unknown: {
        fullName: "unknown",
        firstName: "unknown",
        lastName: "unknown",
        personality: "unknown",
        gender: "unknown",
        age: 0,
        occupation: "unknown",
        voicedBy: "unknown",
    },
};

module.exports = charDB;
